// app/layout.tsx

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TripPlanProvider } from "./context/TripPlanContext";
import { AuthProvider } from "./context/AuthContext";
import { NavigationProvider } from "./context/NavigationContext";
import AuthGuard from "./components/AuthGuard";
import TransitionProvider from "./TransitionProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* 
        Next.js 会自动处理 head 标签, 
        但为了清晰地添加外部样式表, 我们可以显式地写出 <head> 标签。
      */}
      <head>
        {/* --- 在这里添加高德地图的 CSS 链接 --- */}
        <link
          rel="stylesheet"
          href="https://a.amap.com/jsapi_demos/static/demo-center/css/demoutils.css"
        />
        {/* ------------------------------------ */}
      </head>

      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NavigationProvider>
          <AuthProvider>
            <AuthGuard>
              <TripPlanProvider>
                <TransitionProvider>{children}</TransitionProvider>
              </TripPlanProvider>
            </AuthGuard>
          </AuthProvider>
        </NavigationProvider>
      </body>
    </html>
  );
}